listen = "127.0.0.1:8080"
db_path = "./tiering.db"

[upstreams.hot]
order = 1
base_url = "http://127.0.0.1:9090"
addressing_style = "path"
max_age = "30d 25m 2s"
s3_access_key = "key"
s3_secret = "secret"
region = "us-east-1"

[upstreams.cold]
order = 2
name = "cold"
base_url = "http://127.0.0.1:9091"
addressing_style = "path"
s3_access_key = "key"
s3_secret = "secret"
region = "us-east-1"
