name: "Build and push docker image"
on:
  push:
jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v5
    - name: Set up netrc attic login
      id: setup-netrc
      run: |
        NETRC_DIR="$(mktemp -d)"
        echo "machine attic.ialistannen.de" > "$NETRC_DIR/attic-netrc"
        echo "password ${{ secrets.ATTIC_TOKEN }}" >> "$NETRC_DIR/attic-netrc"
        echo "netrc-dir=$NETRC_DIR" >> $GITHUB_OUTPUT
    - uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          substituters = https://attic.ialistannen.de/parkhaus https://cache.nixos.org
          trusted-public-keys = parkhaus:vVkXGxgJxuIN3tmnnefF1rffCRC8IDVsOpjwAiTsSFA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          netrc-file = ${{ steps.setup-netrc.outputs.netrc-dir }}/attic-netrc
    - name: Set up attic
      run: |
        NIXPKGS_OVERRIDE="github:NixOS/nixpkgs/$(jq -r '.nodes.nixpkgs.locked.rev' flake.lock)"
        nix profile install $NIXPKGS_OVERRIDE#attic-client $NIXPKGS_OVERRIDE#nix-fast-build
        attic login mine https://attic.ialistannen.de ${{ secrets.ATTIC_TOKEN }}

        # Save original store paths
        nix path-info --all --json | jq 'keys' > /tmp/original-paths.json
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build parkhaus
      run: |
        # Best effort upload parallel to build
        attic watch-store parkhaus &
        nix-fast-build --no-nom --flake ".#packages.$(nix eval --raw --impure --expr builtins.currentSystem).docker"
        mv result- result
        sha256sum result
    - name: Load docker image
      run: |
        echo "IMG=$(docker load --quiet < result | sed -E 's/.+?: (.+)/\1/g')" >> $GITHUB_ENV
    - name: Push docker images
      run: |
        docker tag "$IMG" ghcr.io/i-al-istannen/parkhaus:$GITHUB_SHA
        docker tag "$IMG" ghcr.io/i-al-istannen/parkhaus:${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}

        # Tag with version and latest if a tag was pushed
        if [[ "$GITHUB_REF" == refs/tags/* ]]; then
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          docker tag "$IMG" ghcr.io/i-al-istannen/parkhaus:$TAG_NAME
          docker tag "$IMG" ghcr.io/i-al-istannen/parkhaus:latest
        fi

        docker rmi "$IMG"
        docker push --all-tags ghcr.io/i-al-istannen/parkhaus
    - name: Upload store to attic
      if: always()
      run: |
        # Save new store paths
        nix path-info --all --json | jq 'keys' > /tmp/new-paths.json

        jq -r -s '(.[1] - .[0]) | .[]' /tmp/original-paths.json /tmp/new-paths.json | attic push parkhaus --stdin
